[colors]
draw_bold_text_with_bright_colors = true
transparent_background_colors = true

[colors.bright]
black = "#777C85"
blue = "#6AB0F3"
cyan = "#76D4D6"
green = "#76D4D6"
magenta = "#E1A6F2"
red = "#F2777A"
white = "#FFFFFF"
yellow = "#FFEEA6"

[colors.normal]
black = "#2D2D2D"
blue = "#6AB0F3"
cyan = "#76D4D6"
green = "#55A860"
magenta = "#E1A6F2"
red = "#F2777A"
white = "#B3B9C5"
yellow = "#FFD479"

[colors.primary]
background = "#2D2D2D"
foreground = "#B3B9C5"

[colors.selection]
background = "#E7DD18"
text = "CellBackground"

[font.normal]
family = "MesloLGS NF"

[window]
dynamic_title = true
opacity = 0.85
