window:
  # window opacity - 0.0 - 1.0 where 1.0 is opaque
  #opacity: 0.8
  opacity: 0.85

  # allow programs to change title
  dynamic_title: true

font:
  normal:
    family: "MesloLGS NF"

key_bindings:
  - { key: N, mods: Command, action: CreateNewWindow }

draw_bold_text_with_bright_colors: true

# Cursor colors

# Colors (New Moon)
colors:
  # Default colors
  primary:
    background: '#2D2D2D'
    foreground: '#B3B9C5'
  # Normal colors
  normal:
    black: '#2D2D2D'
    red: '#F2777A'
    #green: '#92D192'
    green: '#55A860'
    yellow: '#FFD479'
    blue: '#6AB0F3'
    magenta: '#E1A6F2'
    cyan: '#76D4D6'
    white: '#B3B9C5'
  # Bright colors
  bright:
    black: '#777C85'
    red: '#F2777A'
    green: '#76D4D6'
    yellow: '#FFEEA6'
    blue: '#6AB0F3'
    magenta: '#E1A6F2'
    cyan: '#76D4D6'
    white: '#FFFFFF'
  transparent_background_colors: true

  selection:
    text: CellBackground
    #background: '#049EFB'
    background: '#E7DD18'
